competition/urls.py
from django.conf.urls import url
from . import views
from feeds import RssCompetitionsFeed, AtomCompetitionsFeed

urlpatterns = [
    url(r'^$', views.CompetitionListView.as_view(), name='index'),
    url(r'^rss/$', RssCompetitionsFeed(), name='rss'),
    url(r'^atom/$', AtomCompetitionsFeed(), name='atom'),
    url(r'^(?P<pk>\d+)/$', views.detail_redirect, name='detail'),
    url(r'^search/$', views.SearchCompetitionListView.as_view(), name='search'),
]

ml_training/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import views

admin.autodiscover()

urlpatterns = [
    # url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include('competition.urls', namespace='competition')),
    url(r'^admin/', include(admin.site.urls)),
]

# urlpatterns += i18n_patterns()

handler404 = views.handler404
handler403 = views.handler403
handler500 = views.handler500

competition/models.py
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone

import datetime


class Link(models.Model):
    class Meta:
        verbose_name = _('link')
        verbose_name_plural = _('links')
        ordering = ['title']

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    TARGET_CHOICES = (
        ('EM', ''),
        ('BL', '_blank'),
        ('SF', '_self'),
        ('PR', '_parent'),
        ('TP', '_top'),
    )

    title = models.CharField(max_length=200, verbose_name=_('title'))
    href = models.CharField(max_length=200, verbose_name=_('href'))
    target = models.CharField(max_length=2, choices=TARGET_CHOICES, default='EM', verbose_name=_('target'))


class Competition(models.Model):
    class Meta:
        verbose_name = _('competition')
        verbose_name_plural = _('competitions')
        ordering = ['finish_date']

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('competition:detail', kwargs={'pk': self.pk})

    def get_image_url(self):
        return self.image or None

    @property
    def is_finished(self):
        now = timezone.now()
        return now > self.finish_date

    title = models.CharField(max_length=200, verbose_name=_('title'))
    content = models.TextField(verbose_name=_('description'))
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name=_('published date'))
    upd_date = models.DateTimeField(auto_now=True, verbose_name=_('updated date'), blank=True)
    start_date = models.DateTimeField(
        verbose_name=_('start date'),
        default=datetime.datetime.combine(datetime.date.today(), datetime.time(0, 0, 0)),
        blank=False)
    submission_deadline = models.DateTimeField(
        default=datetime.datetime.combine(datetime.date.today(), datetime.time(23, 59, 59)),
        verbose_name=_('submission deadline'))
    entry_deadline = models.DateTimeField(
        default=datetime.datetime.combine(datetime.date.today(), datetime.time(23, 59, 59)),
        verbose_name=_('entry deadline'))
    finish_date = models.DateTimeField(
        verbose_name=_('finish date'),
        default=datetime.datetime.combine(datetime.date.today(), datetime.time(23, 59, 59)),
        blank=False)
    active = models.BooleanField(default=True, verbose_name=_('active?'))
    image = models.URLField(verbose_name=_('url for logo'))
    link = models.URLField(verbose_name=_('site link'), blank=False)
    links = models.ManyToManyField(Link, verbose_name=_('links'), blank=True)
    author = models.ForeignKey(User, verbose_name=_('author'), default=1)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = _('was published recently?')


class Material(models.Model):
    class Meta:
        verbose_name = _('analysis')
        verbose_name_plural = _('analyses')

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

    title = models.CharField(max_length=200, verbose_name=_('title'))
    article = models.URLField(verbose_name=_('article link'), blank=True)
    video = models.URLField(verbose_name=_('video link'), blank=True)
    slides = models.URLField(verbose_name=_('slides link'), blank=True)
    code = models.URLField(verbose_name=_('code link'), blank=True)
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE)

competition/views.py
from itertools import chain

from django.conf import settings
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.views.decorators.cache import never_cache
from django.views import generic
from django.utils.translation import ugettext as _

import re

from models import Competition


class SearchMixin(object):

    @staticmethod
    def normalize_query(query_string,
                        findterms=re.compile(r'"([^"]+)"|(\S+)').findall,
                        normspace=re.compile(r'\s{2,}').sub):
        return [normspace(' ', (t[0] or t[1]).strip()) for t in findterms(query_string)]

    def get_query(self, query_string, search_fields):
        # Query to search for every search term
        query = None
        terms = self.normalize_query(query_string)
        for term in terms:
            # Query to search for a given term in each field
            or_query = None
            for field_name in search_fields:
                q = Q(**{"%s__icontains" % field_name: term})
                if or_query is None:
                    or_query = q
                else:
                    or_query = or_query | q
            if query is None:
                query = or_query
            else:
                query = query | or_query
        return query


class NeverCacheMixin(object):

    @classmethod
    def as_view(cls, **initkwargs):
        view = super(NeverCacheMixin, cls).as_view(**initkwargs)
        return never_cache(view)


class FilterListMixin(generic.ListView):
    filter_by = 'active'

    def _get_queryset(self, queryset=None):
        if not queryset:
            queryset = super(FilterListMixin, self).get_queryset()
        queryset = queryset.filter(active__exact=True)
        self.filter_by = self.request.GET[settings.FILTER_KEY].strip() \
            if settings.FILTER_KEY in self.request.GET else 'active'
        if self.filter_by not in ['active', 'finished', 'all']:
            self.filter_by = 'active'
        active_queryset = []
        finished_queryset = []
        if self.filter_by == 'active' or self.filter_by == 'all':
            active_queryset = queryset.filter(finish_date__gte=timezone.now()).order_by('finish_date')
        if self.filter_by == 'finished' or self.filter_by == 'all':
            finished_queryset = queryset.filter(finish_date__lte=timezone.now()).order_by('-finish_date')

        queryset = list(chain(active_queryset, finished_queryset))
        return queryset

    def get_queryset(self):
        return self._get_queryset()

    def get_context_data(self, **kwargs):
        context = super(FilterListMixin, self).get_context_data(**kwargs)
        context[settings.FILTER_KEY] = self.filter_by
        return context


class CompetitionListView(NeverCacheMixin, FilterListMixin):
    model = Competition
    template_name = 'competition/competition_list.html'
    context_object_name = 'competitions'
    paginate_by = 20


class CompetitionDetailView(NeverCacheMixin, generic.DetailView):
    model = Competition

    def get(self, request, *args, **kwargs):
        content = super(CompetitionDetailView, self).get(request, *args, **kwargs)
        if not (request.user.is_staff or self.object.active):
            raise PermissionDenied
        return content

    def get_context_data(self, **kwargs):
        context = super(CompetitionDetailView, self).get_context_data(**kwargs)
        if self.request.user.is_staff or self.object.active:
            context['title'] = self.get_object().title
        return context


class SearchCompetitionListView(SearchMixin, CompetitionListView):
    template_name = 'competition/search_competition.html'

    def get_queryset(self):
        queryset = Competition.objects.all()
        if ('q' in self.request.GET) and self.request.GET['q'].strip():
            query_string = self.request.GET['q'].strip()
            entry_query = self.get_query(query_string, ['title', 'content'])
            queryset = queryset.filter(entry_query)

        return self._get_queryset(queryset)

    def render_to_response(self, context, **response_kwargs):
        if self.request.is_ajax():
            self.template_name = 'competition/search_competition_ajax.html'
        return super(SearchCompetitionListView, self).render_to_response(
            context, **response_kwargs)

    def get_context_data(self, **kwargs):
        context = super(SearchCompetitionListView, self).get_context_data(**kwargs)
        if ('q' in self.request.GET) and self.request.GET['q'].strip():
            context['query'] = self.request.GET['q'].strip()
            context['title'] = self.request.GET['q'].strip()
        else:
            context['query'] = ''
            context['title'] = _('Search')
        return context


def detail_redirect(request, pk):
    competition = get_object_or_404(Competition, pk=pk)
    return HttpResponseRedirect(competition.link)

competition/templates/competition/competition_detail.html
{# UNUSED #}
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="media competition-detail" data-id="{{ competition.id }}">
        <div class="media-left">
            <a href="{{ competition.link }}" target="_blank">
                <img src="{{ competition.image }}" alt="Logo" class="media-object" style="width: 150px;">
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading competition-title">{{ competition.title|title }}</h4>
            <div><a href="{{ competition.link }}" target="_blank">{% trans "Competition site" %}</a></div>
            <div class="competition-date">{% trans "start date" %}: {{ competition.start_date|date }}</div>
            <div class="competition-date">{% trans "entry deadline" %}: {{ competition.entry_deadline|date }} ({% trans "remaining" %} {{ competition.entry_deadline|timeuntil }})</div>
            <div class="competition-date">{% trans "submission deadline" %}: {{ competition.submission_deadline|date }} ({% trans "remaining" %} {{ competition.submission_deadline|timeuntil }})</div>
            <div class="competition-date">{% trans "finish date" %}: {{ competition.finish_date|date }} ({% trans "remaining" %} {{ competition.finish_date|timeuntil }})</div>
            <hr>
            <div class="more-information">
                {{ competition.content|safe }}
                {% if competition.links.all %}
                    <div>{% trans "Materials" %}:</div>
                    <ul>
                    {% for link in competition.links.all %}
                        <li>
                            <a href="{{ link.href }}" target="{{ link.target }}">{{ link.title }}</a>
                        </li>
                    {% endfor %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

competition/templates/competition/competition_iterator.html
{% load i18n %}
<div class="competition-filter row">
    <div class="col-md-7">{% include "search-form.html" %}</div>
</div>
<div class="competition-list">
{% for competition in competitions %}
    <div class="media competition-item {{ competition.is_finished|yesno:'_finished,_active' }}" data-id="{{ competition.id }}">
        <div class="media-left">
            <a href="{{ competition.link }}" target="_blank">
                <img src="{{ competition.image }}" alt="Logo" class="media-object" style="width: 150px;">
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading competition-title">
                <a href="{{ competition.link }}" target="_blank">{{ competition.title }}</a>
            </h4>
            <div class="competition-date">
                {{ competition.start_date|date }} &mdash; {{ competition.finish_date|date }}
                {% if competition.is_finished %}(<strong>{% trans "finished" %}</strong>){% endif %}
            </div>
            {% if not competition.is_finished %}
                <div class="competition-date">{% trans "Remaining" %} {{ competition.finish_date|timeuntil }}</div>
            {% endif %}
            <div class="competition-details">
                <div class="competition-description">{{ competition.content|safe }}</div>
                {% if competition.material_set.count %}
                    <div class="competition-materials">
                        <h5>{% trans "Analyses" %}:</h5>
                        <ul>
                        {% for material in competition.material_set.all %}
                            <li>
                                {% if material.article %}
                                    <a href="{{ material.article }}" target="_blank">{{ material.title }}</a>
                                {% else %}
                                    <span>{{ material.title }}</span>
                                {% endif %}
                                {% if material.video or material.slides or material.code %}
                                    <div class="btn-group">
                                    {% if material.video %}
                                        <a class="btn btn-default btn-xs" href="{{ material.video }}" target="_blank">
                                            <i class="fa fa-video-camera"></i>
                                        </a>
                                    {% endif %}
                                    {% if material.slides %}
                                        <a class="btn btn-default btn-xs" href="{{ material.slides }}" target="_blank">
                                            <i class="fa fa-picture-o"></i>
                                        </a>
                                    {% endif %}
                                    {% if material.code %}
                                        <a class="btn btn-default btn-xs" href="{{ material.code }}" target="_blank">
                                            <i class="fa fa-github"></i>
                                        </a>
                                    {% endif %}
                                    </div>
                                {% endif %}
                            </li>
                        {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% empty %}
    <div class="jumbotron">
        <h1>{% trans "Oops, no competitions found" %}</h1>
    </div>
{% endfor %}
</div>

{% if is_paginated %}
<div class="text-center">
    <ul class="pagination">
        {% for num in paginator.page_range %}
            {% ifequal num page_obj.number %}
                <li class="active"><a>{{ num }}</a></li>
            {% else %}
                <li><a href="?{{ request.META.QUERY_STRING }}&page={{ num }}">{{ num }}</a></li>
            {% endifequal %}
        {% endfor %}
    </ul>
</div>
{% endif %}

competition/templates/competition/competition_iterator_simple.html
{% load i18n %}
{% if competitions %}
    <table class="table table-condensed table-hover table-striped competition-list">
        <col width="60%">
        <col align="left">
    {% for competition in competitions %}
        {% if competition.active %}
            <tr class="competition-item">
                <td>
                    <a href="{% url 'competition:detail' competition.id %}" class="competition-title">{{ competition.title|title }}</a>
                </td>
                <td>
                    <span class="competition-date">{{ competition.start_date|date:'SHORT_DATE_FORMAT' }}</span> &mdash; <span class="competition-date">{{ competition.finish_date|date:'SHORT_DATE_FORMAT' }}</span>
                </td>
            </tr>
        {% endif %}
    {% endfor %}
    </table>
{% else %}
    <h3>{% trans "Oops, no competitions found" %}</h3>
{% endif %}

competition/templates/competition/competition_list.html
{% extends "base.html" %}

{% block content %}
    {% include "competition/competition_iterator.html" with competitions=competitions %}
{% endblock %}

competition/templates/competition/search_competition.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <h2>{% blocktrans trimmed %}
        Search results for <em>{{ query }}</em>
    {% endblocktrans %}</h2>
    <hr>
    {% include 'competition/competition_iterator.html' with competitions=competitions %}
{% endblock %}

competition/templates/competition/search_competition_ajax.html
{% include 'competition/competition_iterator_simple.html' with competitions=competitions %}