competition/urls.py
from django.conf.urls import url
from . import views
from feeds import RssCompetitionsFeed, AtomCompetitionsFeed

urlpatterns = [
    url(r'^$', views.CompetitionListView.as_view(), name='index'),
    url(r'^rss/$', RssCompetitionsFeed(), name='rss'),
    url(r'^atom/$', AtomCompetitionsFeed(), name='atom'),
    url(r'^(?P<pk>\d+)/$', views.detail_redirect, name='detail'),
    url(r'^search/$', views.SearchCompetitionListView.as_view(), name='search'),
]

ml_training/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import views

admin.autodiscover()

urlpatterns = [
    # url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include('competition.urls', namespace='competition')),
    url(r'^admin/', include(admin.site.urls)),
]

# urlpatterns += i18n_patterns()

handler404 = views.handler404
handler403 = views.handler403
handler500 = views.handler500

ml_training/views.py
from django.shortcuts import render
from django.utils.translation import ugettext as _


def handler403(request):
    print(request)
    return render(request, 'error.html', {
        'error': '403',
        'title': _('Access Denied')
    })


def handler404(request):
    return render(request, 'error.html', {
        'error': '404',
        'title': _('Not Found')
    })


def handler500(request):
    return render(request, 'error.html', {
        'error': '500',
        'title': _('Server Error')
    })

ml_training/templates/analytics.html
<!-- Yandex.Metrika counter --> <script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter37556985 = new Ya.Metrika({ id:37556985, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, trackHash:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks"); </script> <noscript><div><img src="https://mc.yandex.ru/watch/37556985" style="position:absolute; left:-9999px;" alt="" /></div></noscript> <!-- /Yandex.Metrika counter -->

ml_training/templates/base.html
{% load static %}
{% load i18n %}
{% get_current_language as lang %}
<!DOCTYPE html>
<html lang="{{ lang }}">
<head>
    <meta charset="UTF-8">
    <title>{{ title|default:TITLE }}{% if title %}{{ ' | ' }}{{ TITLE }}{% endif %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="description" content="{% trans DESCRIPTION %}">

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
    <div class="container">
        <div class="page-header">
            <a href="{% url 'competition:index' %}"><h1>{{ TITLE }}</h1></a>
            <p class="lead">{{ DESCRIPTION }}</p>
            <p>
                <a href="https://www.facebook.com/groups/1413405125598651/1726705587601935/" target="_blank">{% trans "Facebook" %}</a>,
                <a href="https://www.youtube.com/channel/UCeq6ZIlvC9SVsfhfKnSvM9w" target="_blank">{% trans "YouTube" %}</a>
                <span class="pull-right"><a href="https://docs.google.com/forms/d/1G7j55KHLexuBX3k0he_19CuKMvnGgss8aFEvy3LGNwo/viewform" target="_blank">{% trans "Notify about the competition" %}</a></span>
            </p>
        </div>

        {% block content %}{% endblock %}

        <hr>

        <footer class="row">
            <div class="col-sm-6">{{ TITLE }} &mdash; {% now 'Y' %}</div>
{#            <div class="col-sm-6">{% include "form-choose-lang.html" %}</div>#}
        </footer>
    </div>

    {% include 'analytics.html' %}

    <script src="//code.jquery.com/jquery-2.2.3.min.js" integrity="sha256-a23g1Nt4dtEYOj7bR+vTu7+T8VP13humZFBJNIYoEJo=" crossorigin="anonymous"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'js/search.js' %}"></script>
    <script src="{% static 'js/competitions.js' %}"></script>
    <script src="{% static 'js/i18n.js' %}"></script>
</body>
</html>

ml_training/templates/error.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
    <h1>{{ error }}: {{ title|title }}</h1>
</div>
{% endblock %}

ml_training/templates/form-choose-lang.html
{% load static %}
{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}
<form action="{% url 'set_language' %}" method="post" class="pull-right i18n-form">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ redirect_to }}" />
    {% for language in languages %}
        <input type="radio" class="hidden" name="language" value="{{ language.code }}" id="lang-{{ language.code }}">
    {% endfor %}
    <div class="btn-group" role="group">
    {% for language in languages %}
        <button
                type="button"
                class="btn btn-xs {% if language.code == LANGUAGE_CODE %}btn-success{% else %}btn-default{% endif %}"
                data-for="lang-{{ language.code }}"
        >
            <img src="{% get_static_prefix %}img/{{ language.code }}.png" alt="{{ language.code }}" width="20px">
        </button>
    {% endfor %}
    </div>
</form>

ml_training/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="row">

    <!-- SNA Хакатон -->
    <div class="media">
        <div class="media-left">
            <a href="http://www.snahackathon.org/">
                <img height="100" class="media-object" src="//pp.vk.me/c633521/v633521361/12e88/OxKFOGS9uBw.jpg" alt="SNA Хакатон 2016">
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading">SNA Хакатон 2016</h4>
            <a href="http://www.snahackathon.org/">Сайт соревнования</a>

            <ul>
                <li>
                    <a href="https://www.kaggle.com/klunev">Кирилл Лунев</a>, <a href="https://www.kaggle.com/romario">Роман Халкечев</a> <br/>
                    <a href="https://youtu.be/huE7OEOESng">видео</a>, слайды
                </li>
                <li>
                    Вячеслав Мурашкин <br/>
                    <a href="https://youtu.be/ZCzl-a6y8nQ">видео</a>, слайды
                </li>
            </ul>
        </div>
    </div>


    <!-- Yelp -->
    <div class="media">
        <div class="media-left">
            <a href="https://www.kaggle.com/c/yelp-restaurant-photo-classification" target="_blank">
                <img height="100" class="media-object" src="//kaggle2.blob.core.windows.net/competitions/kaggle/4829/logos/front_page.png" alt="Kaggle Competition: Yelp Restaurant Photo Classification">
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading">Kaggle: Yelp Restaurant Photo Classification</h4>
            <a href="https://www.kaggle.com/c/yelp-restaurant-photo-classification">Соревнование</a> | <a href="https://www.kaggle.com/c/yelp-restaurant-photo-classification/leaderboard">Лидерборд</a>

            <ul>
                <li>
                    <a href="https://www.kaggle.com/zimovnov">Андрей Зимовнов</a> <br/>
                    <a href="https://youtu.be/6EoFq0NaiO8">видео</a>, слайды
                </li>
            </ul>
        </div>
    </div>


    <!-- Баскетбол -->
    <div class="media">
        <div class="media-left">
            <a href="https://www.kaggle.com/c/march-machine-learning-mania-2016">
                <img height="100" class="media-object" src="//kaggle2.blob.core.windows.net/competitions/kaggle/4862/logos/front_page.png" alt="Kaggle competition: March Machine Learning Mania 2016">
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading">Kaggle: March Machine Learning Mania 2016</h4>
            <a href="https://www.kaggle.com/c/march-machine-learning-mania-2016">Соревнование</a> | <a href="https://www.kaggle.com/c/march-machine-learning-mania-2016/leaderboard">Лидерборд</a>

            <ul>
                <li>
                    <a href="https://www.kaggle.com/ciroel">Антон Смердов</a> <br/>
                    <a href="https://youtu.be/w0xcVXevv8c">видео</a>, слайды
                </li>
            </ul>
        </div>
    </div>

</div>
{% endblock %}

ml_training/templates/search-form.html
{% load i18n %}
<form class="input-group search-form" method="get" action="{% url 'competition:search' %}?{{ FILTER_KEY }}={{ filter }}">
    <div class="input-group-btn">
        <a class="btn btn-sm btn-{% if filter == 'active'%}primary{% else %}default{% endif %}" data-{{ FILTER_KEY }}="active">{% trans "Active" %}</a>
        <a class="btn btn-sm btn-{% if filter == 'finished'%}primary{% else %}default{% endif %}" data-{{ FILTER_KEY }}="finished">{% trans "Finished" %}</a>
        <a class="btn btn-sm btn-{% if filter == 'all'%}primary{% else %}default{% endif %}" data-{{ FILTER_KEY }}="all">{% trans "All" %}</a>
    </div>
    <input
        type="text"
        name="q"
        class="form-control input-sm search-input"
        placeholder="{% trans "Search" %}"
        autocomplete="off"
    >
    <div class="input-group-btn">
        <div class="btn-group hidden">
            <button type="button" class="btn btn-sm btn-default dropdown-toggle search-filter" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="glyphicon glyphicon-cog"></i></button>
            <ul class="dropdown-menu dropdown-menu-right">
                <li><a href="#" class="for-actual" data-type="checkbox"><input type="checkbox" name="actual" class="hidden" />{% trans "Choose active" %}</a></li>
            </ul>
        </div>

        <button type="submit" class="btn btn-sm btn-default">
            <i class="fa fa-search"></i>
        </button>
    </div>
</form>
<div class="search-preview popover bottom">
    <div class="arrow"></div>
    <h3 class="popover-title">{% trans "Results" %}</h3>
    <div class="popover-content"></div>
</div>